### ISSUE TITLE
Seeing "<link rel="canonical" href="http://localhost:4000/">" in prod files?

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#10]
See: https://github.com/edgi-govdata-archiving/100days/search?utf8=%E2%9C%93&q=%3Clink+rel%3D%22canonical%22+href%3D%22http%3A%2F%2Flocalhost%3A4000%2F%22%3E&type=

I think we need to rebuild static and ensure we are only pulling down the static site, not templates to productions

**Comment by patcon** [comment]
Thanks! Fixed in #14
