### ISSUE TITLE
CH1.png missing

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#11]
I think an issue with relative path is causing this console error: 
<img width="804" alt="screen shot 2017-06-19 at 10 59 09 am" src="https://user-images.githubusercontent.com/4692834/27291498-5d1e0d38-54de-11e7-9e64-61d8dfbca8b7.png">

Can fix here I think: https://github.com/edgi-govdata-archiving/100days/search?utf8=%E2%9C%93&q=assets%2FCH1.png&type=

**Comment by shaqsingh** [comment]
i should have done these in a branch sry
