### ISSUE TITLE
Javascript not loading (mixed content?)

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#12]
Looks like we aren't using https for JS loads (and maybe we want to serve locally anyway): https://github.com/edgi-govdata-archiving/100days/search?utf8=%E2%9C%93&q=script&type=

Convo from: 
https://edgi.slack.com/archives/C4ER5PRD0/p1497883588497433

I think related to #4

**Comment by patcon** [comment]
Should be fixed in https://github.com/edgi-govdata-archiving/100days/pull/14
