### ISSUE TITLE
403 on CC license image

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#13]
Not able to load CC license image:
<img width="1072" alt="screen shot 2017-06-19 at 1 00 53 pm" src="https://user-images.githubusercontent.com/4692834/27296570-5c024c46-54ef-11e7-8ca9-6c1cb1f29522.png">

<img width="804" alt="screen shot 2017-06-19 at 10 59 09 am" src="https://user-images.githubusercontent.com/4692834/27296561-4c1c572c-54ef-11e7-91c5-4a9e8c912c73.png">

I think the best fix is to add to assets instead of loading remotely, but that tends to be my preference. Any thoughts @shaqsingh and @patcon

**Comment by janakrajchadha** [comment]
That's rather surprising @dcwalk , I didn't face this issue.
![image](https://user-images.githubusercontent.com/13016251/27297112-2df39c5e-5541-11e7-870c-ac13fa5c2f5a.png)

**Comment by patcon** [comment]
Yeah, my browser seems to do redirects for images too @janakrajchadha, to https://licensebuttons.net/l/by-nc-sa/4.0/80x15.png

But I'll update in #14, since i already touch that line, and it would be a merge conflict

**Comment by patcon** [comment]
Fixed over there.
