### ISSUE TITLE
Horizontal alignment of Peer Reviews section on wide screens

### ISSUE THREAD

**Issue by suchthis** [edgi-govdata-archiving/100days#16]
Looks like the horizontal alignment isn't working quite as intended for the Peer Reviews section; I believe image should center and scale with charcoal background, as it does on main report page.

**Comment by suchthis** [comment]
![peer-reviews-alignment](https://user-images.githubusercontent.com/3578439/27300969-73caf0de-54e6-11e7-98a1-93c787466f32.png)

**Comment by suchthis** [comment]
Hey @shaqsingh I see you closed this issue but I'm still seeing it now, in Safari 9.0.3 and Chrome 58.0.3029.110 on OSX El Cap. 

@dcwalk was this one of the items in your branch?

**Comment by dcwalk** [comment]
Hmmm, I tested and had resolved in chrome, safari, and ff this was closed automatically via a commit that has been deployed. Can you clear your cache and test again?

I can't reproduce...  58.0.3029.110 (64-bit) on sierra (10.12.5).
<img width="1247" alt="screen shot 2017-06-20 at 10 53 56 pm" src="https://user-images.githubusercontent.com/4692834/27364958-7ad94418-560b-11e7-9d6e-fa7dfdec2b21.png">


Lets reopen if you still have the problem after clearing?
