### ISSUE TITLE
Quick possible updates

### ISSUE THREAD

**Issue by suchthis** [edgi-govdata-archiving/100days#17]
These definitely aren't issues but just a couple ideas for quick updates that might be nice:

- [x] Make the words "download the PDF" a link to the PDF as well, on this page: https://envirodatagov.org/publication/the-epa-under-siege/, just for folks that aren't familiar with the PDF viewer and which button is the download.

- [x] Space the whole report out a bit more, for easier reading (between paragraphs and around pullout quotes), but especially add and standardize spacing before section headings. If we could use the same spacing that we do above "IX. APPENDIX: INTERVIEW COMPENDIUM" above the other section headings, it'd be nice to be consistent and seems like that spacing works a bit better.

- [x] Match the formatting of the figure captions to that of the table caption, which is indented from the body copy. Would be nice to be consistent and that seems to work a bit better to delineate the caption from the body.

EDIT: @patcon turned into checklist

**Comment by dcwalk** [comment]
I've added the button on the publication to reflect how other publications are set up (cc @lourdesvera)

**Comment by suchthis** [comment]
Hey @shaqsingh I see you closed this issue, but the 2nd two items haven't been done. Did we decide we didn't want to do those?

**Comment by dcwalk** [comment]
I think the bottom two have been addressed in https://github.com/edgi-govdata-archiving/100days/pull/25, hence closing. I've reopened just to ensure the templating yaml bit remains, but this hasn't been deployed

**Comment by suchthis** [comment]
Ah, thanks @dcwalk. Re. #2: I see that you changed the spacing above the Appendix to match that used elsewhere above section headings. I was thinking we might want to actually update the other section headings to match the Appendix (will upload screenshots of how it was, in case this doesn't make sense), so there was more space throughout, and just generally space the report out for easier reading, e.g. add more space between paragraphs and around special items like pullout quotes, before section headings, etc. Since it's so much copy, I thought more whitespace might make it a little more digestible.

But I know everyone is super busy, so if we don't think it's worth making adjustments like this, I totally understand!

**Space before most sections:**

![spacing-sections](https://user-images.githubusercontent.com/3578439/27408633-80948764-5692-11e7-987a-b212d5152327.png)


**Space before Appendix:**


![spacing-appendix](https://user-images.githubusercontent.com/3578439/27408634-809606d4-5692-11e7-96ee-408278773480.png)

**Comment by patcon** [comment]
Hey Ky! Just to clarify for my own understanding, are point (1) and (3) done to the extent of the original ask? And if there are new realizations beyond the original, we should def get them noted in issues, too :)

PS, holy moly, you snagged an awesome username!

**Comment by shaqsingh** [comment]
@suchthis I chose to match Appendix to the rest of the headings because I thought that gap was too big to go throughout. I increased font size and line height but can definitely add more spacing

**Comment by dcwalk** [comment]
re-confirming (and checkboxed) that I've done 1 above -- that is on the main website!
https://envirodatagov.org/publication/the-epa-under-siege/

**Comment by suchthis** [comment]
Yep @patcon #1 and #3 are done. And that's been my handle since IRC days!

Got it, @shaqsingh. My vote would be to increase spacing throughout as I do think it aids readability when there's this much text, and then we'd have better parity with the PDF which is pretty spacious, but if you all like the web version as-is, great!
