### ISSUE TITLE
Accessibility improvements

### ISSUE THREAD

**Issue by shaqsingh** [edgi-govdata-archiving/100days#19]
naming, etc. could be improved for screen reader software

**Comment by dcwalk** [comment]
Awesome! 

@b5 shared this as potentially useful: https://github.com/pa11y/pa11y

**Comment by patcon** [comment]
And this to run via travis ci: https://gist.github.com/adelevie/a222caefe7676440d47b

**Comment by shaqsingh** [comment]
Checklist + pattern library http://a11yproject.com/checklist.html
