### ISSUE TITLE
Add cover image to "coming soon" page

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/100days#2]
Reticketed from https://github.com/edgi-govdata-archiving/100days/pull/1#pullrequestreview-44310502

> EDGI logo makes sense but probably we want some kind of a cover image as well?

cc: @titaniumbones

**Comment by patcon** [comment]
Just my 2c, but I like it as-is. The recent webdev trend of cover images strikes me as introducing lots of page bloat that's a bit hostile to visitors with slow internet speeds ¯\\\_(ツ)\_/¯

**Comment by patcon** [comment]
Example: 3.1 MB for a single image in the slider on the edgi main page :(
https://envirodatagov.org/wp-content/uploads/2017/05/20030403-3525766316_8d71b04961_o.jpg

**Comment by dcwalk** [comment]
Ach I must not have relinked that one :/ we (I) went through and resized a bunch of images on the EDGI site tto try and reduce those... gonna ticket

**Comment by dcwalk** [comment]
I'm not too fussed-- the original ask for the landing page was for the cover image so I threw it up that squashed one. That said, this is just a landing page and I think the focus should be on the next stage :)

**Comment by dcwalk** [comment]
closing as stale, the beautiful site is up 😁
