### ISSUE TITLE
ensure https for subdomain works

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#4]
Moving from Slack (https://edgi.slack.com/archives/C3EF5T7T6/p1497259423181120):
the report is distributed with https:// in the url, we need to make sure that works when visiting the site. 

@patcon -- you dug up that gist: https://gist.github.com/cvan/8630f847f579f90e0c014dc5199c337b
Can you tackle this asap? I'm out until Monday but can revisit then

**Comment by patcon** [comment]
> point the nameservers to CloudFlare's

Hm. We'd have to use cloudflare for our nameservers. This seems less than ideal, so maybe the above isn't the best approach.

This seems part of enforcing redirect from HTTP to HTTPS on namecheap:
https://www.namecheap.com/support/knowledgebase/article.aspx/9770/38/how-to-force-https-using-htaccess-file-in-cpanel

Maybe the right resource to set up our own cert? http://www.cpanelkb.net/how-to-install-wildcard-ssl-certificate/

**Comment by dcwalk** [comment]
The mailout is happening Monday, it seems urgent to get this dealt with before then. @titaniumbones can you assist?

I am not back in toronto until 11pm

**Comment by titaniumbones** [comment]
Ditto

On June 18, 2017 12:59:58 PM EDT, dcwalk <notifications@github.com> wrote:
>The mailout is happening Monday, it seems urgent to get this dealt with
>before then. @titaniumbones can you assist?
>
>I am not back in toronto until 11pm
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/edgi-govdata-archiving/100days/issues/4#issuecomment-309289593

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by patcon** [comment]
I've bumped nshapiro in `#100days_report` on slack to hopefully get me DNS access!

**Comment by shapironick** [comment]
shared cPanel access w/ patona couple hours ago

**Comment by dcwalk** [comment]
Go team!! @patcon and @shapironick thank you for seeing this through.

**Comment by ebarry** [comment]
i'm getting a broken https from this subdomain, haven't visited it before this morning:
![screen shot 2017-06-19 at 11 11 47 am](https://user-images.githubusercontent.com/161439/27292086-3e5ea752-54e0-11e7-8fcc-257f3293a3dc.png)

**Comment by dcwalk** [comment]
Reopening -- @ebarry can you provide some detail on browser (whiche one? mobile? version?)

We know we have some mixed content with js, I think that is the issue here and in #12

**Comment by patcon** [comment]
I think this is dealt with in PR above, so going to re-close for now. Pls track that issue for resolution :)

**Comment by ebarry** [comment]
Looking great now!!!! <3
