### ISSUE TITLE
Consider adding analytics support

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/100days#42]
@shaqsingh was lamenting over drinks the lack of analytics on the 100days site. I will admit she was torn about wanting them, but not liking trackers (if i'm remembering correctly).

We floated the idea of self-hosting analytics, of which I'm aware of [Piwik](https://piwik.org/).

Perhaps we should instead open an issue in overview repo on formulating a general analytics policy?

Related issue for EDGI website: https://github.com/edgi-govdata-archiving/edgi-website/issues/27

**Comment by patcon** [comment]
Related: [`awesome-selfhosted`: Web Analytics](https://github.com/Kickball/awesome-selfhosted/blob/master/README.md#analytics)

**Comment by dcwalk** [comment]
Love the idea of an analytics policy @shaqsingh and @patcon!

I've worked with piwik in the past, in terms of self hosted I'm 👍 . Despite my naysaying in that other issue I also think a thought-through approach to a hosted option is potentially a good fit for EDGI

**Comment by patcon** [comment]
Documented some related tasks in the other thread: https://github.com/edgi-govdata-archiving/edgi-website/issues/27#issuecomment-327750868

**Comment by dcwalk** [comment]
@patcon what is the status of having this launched in time for the report being up on Thursday? I think that would be ideal to be tracking
