### ISSUE TITLE
Include data visualization scripts and document source data

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#43]
I recall with the first chapter there were some visualizations where data processing happened (can't remember if those got cut.

It would be neat in future chapters if we could link from the report to our scripts and document data sources (and seems very EDGI 🥇 to me).

Would that make sense @shaqsingh?

**Comment by patcon** [comment]
Source data was @littlesis-org

If I recall, @shaqsingh was importing their data into [Cytoscape](http://www.cytoscape.org/) at first, until it was decided that it didn't present as cleanly as preferred. I think this was when things were dropped, but shaq def knows more :)
