### ISSUE TITLE
Formatting errors on high-resolution screens

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#44]
From @patcon in https://github.com/edgi-govdata-archiving/edgi-website/issues/41 (repo for main EDGI site):

> See: https://100days.envirodatagov.org/epa-under-siege.html
>
> On a high-resolution screen (like a 4K) or when zooming out to a comparable degree via browser controls, the bottom of the page starts displaying very oddly, with tons of whitespace and a jumpy, glitchy scrollbar. By the way the glitching happens, it might be related to the "Back to Appendix Themes" button that hovers when at the bottom of page.
>
> cc: @dcwalk

**Comment by shaqsingh** [comment]
done in #92
