### ISSUE TITLE
Address feedback on Part 2 review

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#53]
1. ~set up permalinks/redirects~ (addressed in #52)
1. ~update name of peer reviews to match the first part~ (addressed in #52)
1. ~The “DATA METHODOLOGY” nav link points to “pursuing-toxic-agenda-data.html”, but we used just “pursuing-toxic-agenda-data” in the PDF. Are we going to use both and add a redirect?~ (addressed in #52)
1. ~FN 58 it says Colby Texas and it should say Crosby Texas. Is it too late to do anything about this?~  (addressed in #54)
1. ~fix link to the second pdf~  (addressed in #54)
1. ~Colby to Crosby is fixed online.~  (addressed in #55)
1. ~The peer reviews page for Part 2 uses Part 1 image~  (addressed in #55)
1. ~report peer review: fix the background image to part 2 main image~  (addressed in #55) 
1. ~on all subpages clear links back to the report main page and check it work (currently returning an error)~  (addressed in #56) 
1. ~The bottom of the Interview has this text: “EDGI_Logo-1_Hi-Res_Transp.png
Pursuing a Toxic Agenda”~  (addressed in #56) 
1. ~data page: the logo isn't appearing at the bottom of the page~  (addressed in #56) 
1. ~on the data page, @shaq and @wyliesara should be added as authors~ (addressed in #56) 
1. ~all part 2 links have the Google Docs wrapper, this should be removed (i.e., `https://www.google.com/url?q=` at the beginning and a trailing `&amp...` unique per link)~ (addressed in #58) 
1. ~**data** chance page title and nav reference to "data methods"~ (addressed in #58) 
1. ~responsive image sizing fixes~ (addressed in #58) 
1. ~on the mustafa ali interview page the boxes are out of alignment over the image~ (addressed in #56) 
1. ~on main page the header image is being overwhelmed by the second text box~ _appears resolved?_
1. ~**PRIORITY** Colby to Crosby is in the pdf-- this needs to be reuploaded~ Uploaded 2:30pm Sept 19 on envirodatagov.org
1. ~fix the alignment on the data page title~ (addressed in #58) 

---
**bugs/features**
1. ~**PRIORITY** Scaling of images/tiles on homepage and Toxic Agenda pages not working correctly on Safari and Chrome on OSX~ (addressed on 65)
1. ~**PRIORITY** Footnote 58 has been corrected in the PDF and it needs to be reuploaded~ done by @patcon at 5:41pm Sept 19
1. ~**PRIORITY** All links to the interview in the report need to be fixed; all either 404 or do nothing~ https://github.com/edgi-govdata-archiving/100days/pull/59
1. ~Fix alignment of author byline on Part II report page, so it's not cut off at smaller screen widths~ moved to https://github.com/edgi-govdata-archiving/100days/issues/70
1. ~The header/subheader/sub-subheader styling hasn’t been added (all are all-caps)~ DUP of (12) below
1. ~The Chlorpyrifos map key covers a lot of the map and info box on mobile (worth hiding on mobile?)~ migrated to https://github.com/edgi-govdata-archiving/100days/issues/72
1. ~**data** on the data page bold the figure numbers so it's clearer which paragraph is about which figure~ #60 (and #58?) 
1. ~**data** also on the data page add links to the relevant figures~ #60 (and #58) 
1. ~Add link from the text “interview with Mustafa Ali” right before the ToC.~ (addressed in #59)
1. ~Add Interview to icon nav menu~ (addressed in #59)
1. ~the visual links to the interview and part 1 aren't appearing at the bottom of the report page?~ migrated to https://github.com/edgi-govdata-archiving/100days/issues/78
1. ~**data** The header/subheader/sub-subheader styling hasn’t been added (prelim address in #60)~ migrated to https://github.com/edgi-govdata-archiving/100days/issues/71
1. ~There are some extra files we need to trim (imageN vs. part2figureN)~ migrated to https://github.com/edgi-govdata-archiving/100days/issues/77
1. ~Images are not compressed, might want to include 2x scaling for hires~ migrated to https://github.com/edgi-govdata-archiving/100days/issues/76
1. ~**re-enable disqus comments**~ migrated to https://github.com/edgi-govdata-archiving/100days/issues/75
1. ~**data** add data to github and link from data methods page~ migrate to https://github.com/edgi-govdata-archiving/100days/issues/74
1. ~**review commented out sections**~ migrated to https://github.com/edgi-govdata-archiving/100days/issues/73

---
**style/ux**
1. ~Request from Sara: can we float the icon nav menu so it stays visible as the page is scrolled?~ https://github.com/edgi-govdata-archiving/100days/issues/79
1. ~**data** figure numbers at begin of paragraphs should be bolded but I can live without it~ #60
1. ~There’s a stray extra linebreak or two. Maybe one of us should address minor formatting glitches in a PR?~ https://github.com/edgi-govdata-archiving/100days/issues/80
1. ~on peer reviews distinguishing between the review and our revisions~ https://github.com/edgi-govdata-archiving/100days/issues/81
1. ~on both the part 2 and the ali interview page there should be a link back to the overall first 100 days report somewhere, right now the EDGI link takes you there but that should probably take you the main EDGI site?~ https://github.com/edgi-govdata-archiving/100days/issues/82
1. ~the anchor links for the references are slightly off, so if you link to a reference you have to scroll up to see the number referenced.~ https://github.com/edgi-govdata-archiving/100days/issues/83
1. ~Treatment of report page cover image/title not consistent on Part I and Part II (should we just use same layout for Part I as Part II?)~ https://github.com/edgi-govdata-archiving/100days/issues/84
1. ~ULs and the sub- and sub-sub-headings in the ToC are at 1rem font size, rather than the 1.1rem the main body is. Can we make font size consistent in the body and the ToC at least as large as body copy?~ https://github.com/edgi-govdata-archiving/100days/issues/85
1. ~I really think it aids readability of sections if there is more space around subheadings, and especially before them. Ideally, there’s slightly more space above a section heading than below it, so that the heading is visually associated with its content. There’s a lot of space before main headings, which is nice; would be good to add more around sub- and sub-sub-headings, too.~ https://github.com/edgi-govdata-archiving/100days/issues/86
1. ~I think it’s nice to add a little space before/after figures/images, so they’re more distinct from copy.~ https://github.com/edgi-govdata-archiving/100days/issues/87
1. ~Should we consider linking to larger versions of the figures and tables from each, in case anyone wants to zoom in?~ https://github.com/edgi-govdata-archiving/100days/issues/88
1. ~Should we increase the offset of ULs so they stand out a bit more from body copy?~ https://github.com/edgi-govdata-archiving/100days/issues/90
1. ~Should we use same link styling in this site as we do on main EDGI site? No underline and different hover effect?~ https://github.com/edgi-govdata-archiving/100days/issues/89
1. ~If the EDGI logo at top-left is the nav element to the 100 Days homepage, it might be nice to have a link somewhere (just on homepage?) back to main EDGI site~ https://github.com/edgi-govdata-archiving/100days/issues/82

---
**questions**
1.  ~If I zoom out enough on the Chlorpyrifos image to see the whole country, it become a dot map (on desktop and mobile). Is that intended?~
    - This is a limitation of google fusion tables

**Comment by dcwalk** [comment]
Hey @shaqsingh -- just a bump to let you know this is updated as of #58 / 14:52

**Comment by suchthis** [comment]
Hey @dcwalk or @patcon: It looks like someone checked off this item but I'm not seeing that on production (but display very wonky on my machine, so maybe it's there for others?):

>the visual links to the interview and part 1 aren't appearing at the bottom of the report page? (addressed in #56)

**Comment by dcwalk** [comment]
@suchthis -- I took that to mean the missing images at the bottom of the page, which were fixed in #56 . could you clarify what "visual links" means to you/what you are expecting to see?

**Comment by shaqsingh** [comment]
@suchthis I commented out the version I showed on that call because it was half done and I wasn't sure if it should be on the other pages as well

**Comment by suchthis** [comment]
Ah thanks @dcwalk and @shaqsingh! It sounds like that comment from I think Sara isn't done yet, then. I think we were expecting to see the visual links to Part I & the Ali Interview at the bottom of the Part II page that we saw demo'ed on the last design call. Sounds like those aren't done yet, but it might be nice to just add a text link to the Interview at the bottom of the report page in the meantime.

**Comment by dcwalk** [comment]
🙏 thanks for breaking these apart @patcon!

**Comment by patcon** [comment]
Ok, I believe I've got these all into separate issues, so going to close this for now. Pls re-open if you feel differently :)
