### ISSUE TITLE
Reduce height on Index Part Sections

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#66]
from #65 and [`.section`](https://github.com/edgi-govdata-archiving/100days/pull/65/files#diff-46d5644ae6b8906c8a35d46be22427f9L93) --

> Does this need to be so tall? I feel like we are getting some odd length issues on small screens (i.e. this could be much more compact.) Probably doesn't belong in this PR so I can open an issue

I'm wondering if we could shorten the max-height and probably adjust the `background-position` to better feature elements of each image.

**Comment by shaqsingh** [comment]
done in #92
