### ISSUE TITLE
Fix byline alignment on small screens

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/100days#70]
Re-ticketed from https://github.com/edgi-govdata-archiving/100days/issues/53

> Fix alignment of author byline on Part II report page, so it's not cut off at smaller screen widths

**Comment by patcon** [comment]
Is this margin mis-alignment what you're referring to @suchthis?

![screenshot](https://imgur.com/zKUklt3.png)

**Comment by shaqsingh** [comment]
I can't replicate this?

**Comment by shaqsingh** [comment]
done in #92
