### ISSUE TITLE
Renable disqus comments

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/100days#75]
Re-ticketed from https://github.com/edgi-govdata-archiving/100days/issues/53

> re-enable disqus comments

- [x] log-in and confirm settings? (generate new comment sections)
- [ ] share/add EDGI gmail as acct manager?

**Comment by dcwalk** [comment]
This was done in #92 -- but unclear about the acct manager.

I'll hold off on closing, maybe @shaqsingh you can weigh in?

**Comment by dcwalk** [comment]
Going to close
