### ISSUE TITLE
Issue with logo rendering in firefox

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#8]
Just realized the logo on the stop left doesn't display in FF (comparison with chrome)

<img width="454" alt="screen shot 2017-06-19 at 8 04 10 am" src="https://user-images.githubusercontent.com/4692834/27284317-1bdab532-54c6-11e7-924b-5a09441d86d5.png">

 I'm wondering if the issue is the path in post.css: 
https://github.com/edgi-govdata-archiving/100days/blob/master/assets/post.css#L257

(and related to eventual v. expected deployment)

**Comment by shaqsingh** [comment]
started branch firefox-fixes for this and the basic functionality works but theres little bugs I can't fix until later today (`<sup>` tagged things appear in front of the bar, and responsiveness of width on chrome needs work)
