### ISSUE TITLE
Remove extra linebreaks and other minor formatting issues

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/100days#80]
Re-ticketed from https://github.com/edgi-govdata-archiving/100days/issues/53

> There’s a stray extra linebreak or two. Maybe one of us should address minor formatting glitches in a PR?

**Comment by dcwalk** [comment]
I actually think I caught these in #69, but that is not deployed (as it was minor I figured we'd get a whole batch out first... but now it has been lingering)
