### ISSUE TITLE
Consider how layout can link to both EDGI website and mini site front page

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/100days#82]
Re-ticketed from https://github.com/edgi-govdata-archiving/100days/issues/53

> on both the part 2 and the ali interview page there should be a link back to the overall first 100 days report somewhere, right now the EDGI link takes you there but that should probably take you the main EDGI site?

> If the EDGI logo at top-left is the nav element to the 100 Days homepage, it might be nice to have a link somewhere (just on homepage?) back to main EDGI site

**Comment by shaqsingh** [comment]
done in #92. It's in the footer
