### ISSUE TITLE
Improve spacing around headings

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/100days#86]
Re-ticketed from https://github.com/edgi-govdata-archiving/100days/issues/53

> I really think it aids readability of sections if there is more space around subheadings, and especially before them. Ideally, there’s slightly more space above a section heading than below it, so that the heading is visually associated with its content. There’s a lot of space before main headings, which is nice; would be good to add more around sub- and sub-sub-headings, too.

**Comment by dcwalk** [comment]
This was fixed in #92, closing!
