### ISSUE TITLE
Document how report pages generated from GDoc/PDF content

### ISSUE THREAD

**Issue by patcon** [edgi-govdata-archiving/100days#91]
Re-ticketed from https://github.com/edgi-govdata-archiving/100days/pull/67#issuecomment-335544456

cc: @shaqsingh

**Comment by patcon** [comment]
Feel free to just drop a braindump here, and someone else can clean it up later :)

**Comment by dcwalk** [comment]
@patcon -- could you perhaps take this on at the upcoming post mortem event next week?
