### ISSUE TITLE
Is there a reason we are using Ruby ~> 2.3.3 in Gemfile?

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/100days#99]
Hey @shaqsingh, is there a reason we are using  Ruby ~> 2.3.3?
I've been behind, and now I'm ahead at  2.4.0 and I don't feel comfortable enough with Ruby to know whether there are significant differences.

It appears to me do not have to be so specific, and that would help by reducing the need to manage multiple versions on my end.

**Comment by patcon** [comment]
I think I set that precedent. But seems that ruby no longer lets you remove it?
https://stackoverflow.com/questions/36316399/can-i-stop-bundler-from-adding-ruby-version-to-gemfile-lock

You could just change it for your local setup and not commit it?

**Comment by dcwalk** [comment]
Yeah, I'm wondering if we could also just replace `~>` with `>` and have that in the Gemfile?

**Comment by patcon** [comment]
Just to followup: ">" is def the last case scenario because there's no upper bound. when ruby 3.0 series comes out, our apps would likely break on any hosted platform

**Comment by patcon** [comment]
"~>" is usually the best, either `~> x.y.z` (which caps to "x.y" series) or `~> x.y`, which caps to "x" series

**Comment by dcwalk** [comment]
👍 closing as we've changed our practices :)
